version: 0.2

phases:

  install: 
    runtime-versions:
      python: 3.9
    commands:
      # start up Docker
      - |
        nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
        timeout 15 sh -c "until docker info; do echo .; sleep 1; done" 
      # log into ECR
      - |
        aws ecr get-login-password --region $AWS_DEFAULT_REGION |\
          docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      # Build email forwarding lambda
      - |
        docker build --tag ${APPLICATION}-forward-email:latest \
                      --file Dockerfile \
                      ./lambdas/mail/forward/
        docker tag ${APPLICATION}-forward-email:latest \
                    $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${APPLICATION}-forward-email:latest
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${APPLICATION}-forward-email:latest
      # Build email sending lambda
      - |
        docker build --tag ${APPLICATION}-send-email:latest \
                      --file Dockerfile \
                      ./lambdas/mail/send/
        docker tag ${APPLICATION}-send-email:latest \
                    $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${APPLICATION}-send-email:latest
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${APPLICATION}-send-email:latest
      # Build token lambda
      - |
        docker build --tag ${APPLICATION}-token:latest \
                      --file Dockerfile \
                      ./lambdas/auth/token/
        docker tag ${APPLICATION}-token:latest \
                    $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${APPLICATION}-token:latest
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${APPLICATION}-token:latest
      # Build register lambda
      - | 
        docker build --tag ${APPLICATION}-register:latest \
                      --file Dockerfile \
                      ./lambdas/auth/register/
        docker tag ${APPLICATION}-register:latest \
                    $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${APPLICATION}-register:latest
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${APPLICATION}-register:latest

  post_build:
    commands:
      # Push email forwarding lambda
      - |
        aws lambda update-function-code \
                      --function-name ${APPLICATION}-forward-email \
                      --image-uri $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${APPLICATION}-forward-email:latest
      # Push email sending lambda
      - |
        aws lambda update-function-code \
                      --function-name ${APPLICATION}-send-email \
                      --image-uri $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${APPLICATION}-send-email:latest
      # Push token lambda
      - |
        aws lambda update-function-code \
                      --function-name ${APPLICATION}-token \
                      --image-uri $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${APPLICATION}-token:latest
      # Push register lambda
      - |
        aws lambda update-function-code \
                      --function-name ${APPLICATION}-register \
                      --image-uri $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${APPLICATION}-register:latest